blank_issues_enabled: true
contact_links:
  - name: General support
    url: https://team-190.github.io/190-Software-Knowledge-Base/category/software-engineering-practices
    about: Questions that aren't a bug or feature request
